language: php
php:
   - 5.6
script:
- echo "skipping test f"
env:
  global:
  - 'SFTP_USER=mentalli'
  - 'SFTP_PASSWORD=hJzjHSrTpf'
after_success:
-find . -type d \( -path "./.*" \) -prune -o -name "*" -print -exec curl --ftp-create-dirs -T {} ftp://mentallica.com/public_html/travis-mentallica/ --user ${SFTP_USER}:${SFTP_PASSWORD} \;